[versions]
loom = "1.8.0-alpha.50001"
gson = "2.11.0"

[libraries]
loom = { group = "net.fabricmc", name = "fabric-loom", version.ref = "loom" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }