[versions]
loom = "1.5.7"
gson = "2.10.1"

[libraries]
loom = { group = "net.fabricmc", name = "fabric-loom", version.ref = "loom" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }